namespace YelcoBot.CodeSweep.Domain.Services
{
    public sealed class GeneratedCodeDetector
    {
        private static readonly string[] GeneratedExtensions =
        {
            ".g.cs",
            ".g.i.cs",
            ".designer.cs",
            ".generated.cs",
            ".AssemblyAttributes.cs",
            ".AssemblyAttribute.cs"
        };

        public bool IsGeneratedCode(string filePath, string? fileContent = null)
        {
            if (string.IsNullOrWhiteSpace(filePath))
                return false;

            string lowerPath = filePath.ToLowerInvariant();
            if (lowerPath.Contains(@"\obj\") || lowerPath.Contains("/obj/"))
                return true;

            foreach (string ext in GeneratedExtensions)
            {
                if (lowerPath.EndsWith(ext, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            if (!string.IsNullOrEmpty(fileContent))
            {
                string headerSample = fileContent.Length > 1024 ? fileContent.Substring(0, 1024) : fileContent;
                if (headerSample.Contains("<auto-generated") || headerSample.Contains("<autogenerated"))
                {
                    return true;
                }
            }

            return false;
        }
    }
}
