using FluentAssertions;
using Xunit;
using YelcoBot.CodeSweep.Domain.Services;

namespace YelcoBot.CodeSweep.Domain.Tests.Services
{
    public class GeneratedCodeDetectorTests
    {
        private readonly GeneratedCodeDetector _detector = new GeneratedCodeDetector();

        [Theory]
        [InlineData("File.g.cs")]
        [InlineData("MyComponent.designer.cs")]
        [InlineData("Model.generated.cs")]
        [InlineData("AssemblyInfo.AssemblyAttributes.cs")]
        public void IsGeneratedCode_ShouldReturnTrue_ForGeneratedFileExtensions(string filePath)
        {
            bool result = _detector.IsGeneratedCode(filePath);
            result.Should().BeTrue();
        }

        [Theory]
        [InlineData("UserService.cs")]
        [InlineData("OrderController.cs")]
        public void IsGeneratedCode_ShouldReturnFalse_ForNormalCSharpFiles(string filePath)
        {
            bool result = _detector.IsGeneratedCode(filePath);
            result.Should().BeFalse();
        }

        [Fact]
        public void IsGeneratedCode_ShouldReturnTrue_WhenContentHasAutoGeneratedTag()
        {
            string content = "// <auto-generated>\n// Code generated by tool.\n// </auto-generated>";
            bool result = _detector.IsGeneratedCode("CustomFile.cs", content);
            result.Should().BeTrue();
        }
    }
}
