using System.ComponentModel;
using Community.VisualStudio.Toolkit;
using YelcoBot.CodeSweep.Domain.Options;

namespace YelcoBot.CodeSweep.Infrastructure.VisualStudio.Settings
{
    /// <summary>
    /// Opciones para VS 2022 (Tools → Options clásico). En VS 2026 no se muestra: la reemplaza la página moderna
    /// (CodeSweep.registration.json declara "legacyOptionPageId" con el GUID de esta página).
    /// </summary>
    public class ClassicOptions : BaseOptionModel<ClassicOptions>
    {
        private const string General = "1. General";
        private const string Rules = "2. Cleanup Rules";
        private const string FileTypes = "3. File Types";
        private const string Exclusions = "4. Exclusions";

        [Category(General), DisplayName("Automatic cleanup on save"), Description("Clean each document right before it is saved.")]
        [DefaultValue(false)]
        public bool CleanupOnSave { get; set; } = false;

        [Category(Rules), DisplayName("Remove unused local variables"), Description("CS0168 / CS0219. Skipped when the file has compile errors.")]
        [DefaultValue(true)]
        public bool RemoveUnusedLocalVariables { get; set; } = true;

        [Category(Rules), DisplayName("Remove unused usings"), Description("CS8019. Skipped when the file has compile errors.")]
        [DefaultValue(true)]
        public bool RemoveUnusedUsings { get; set; } = true;

        [Category(Rules), DisplayName("Sort usings"), Description("global → normal → static → alias; System.* first.")]
        [DefaultValue(true)]
        public bool SortUsings { get; set; } = true;

        [Category(Rules), DisplayName("Remove consecutive blank lines"), Description("Keeps at most one blank line in a row, in C# and in files formatted with the editor (except .js/.ts).")]
        [DefaultValue(true)]
        public bool RemoveConsecutiveBlankLines { get; set; } = true;

        [Category(Rules), DisplayName("Format document"), Description("Roslyn formatting; respects your .editorconfig.")]
        [DefaultValue(true)]
        public bool FormatDocument { get; set; } = true;

        [Category(FileTypes), DisplayName("C# (.cs)")]
        [DefaultValue(true)]
        public bool IncludeCSharp { get; set; } = true;

        [Category(FileTypes), DisplayName("Visual Basic (.vb)")]
        [DefaultValue(true)]
        public bool IncludeVisualBasic { get; set; } = true;

        [Category(FileTypes), DisplayName("Web Forms (.aspx, .ascx, .master, .asax)")]
        [DefaultValue(true)]
        public bool IncludeWebForms { get; set; } = true;

        [Category(FileTypes), DisplayName("Regenerate Web Forms designer after formatting"), Description("Web Application projects only. Usually not needed.")]
        [DefaultValue(false)]
        public bool RegenerateWebFormsDesigner { get; set; } = false;

        [Category(FileTypes), DisplayName("Razor (.cshtml, .vbhtml, .razor)")]
        [DefaultValue(true)]
        public bool IncludeRazor { get; set; } = true;

        [Category(FileTypes), DisplayName("HTML (.html, .htm)")]
        [DefaultValue(true)]
        public bool IncludeHtml { get; set; } = true;

        [Category(FileTypes), DisplayName("XML / Config (.xml, .config, .webinfo)")]
        [DefaultValue(true)]
        public bool IncludeXmlConfig { get; set; } = true;

        [Category(FileTypes), DisplayName("XAML (.xaml)")]
        [DefaultValue(true)]
        public bool IncludeXaml { get; set; } = true;

        [Category(FileTypes), DisplayName("Styles (.css, .less, .scss)")]
        [DefaultValue(true)]
        public bool IncludeStyles { get; set; } = true;

        [Category(FileTypes), DisplayName("Scripts (.js, .ts)")]
        [DefaultValue(true)]
        public bool IncludeScripts { get; set; } = true;

        [Category(FileTypes), DisplayName("JSON (.json)")]
        [DefaultValue(true)]
        public bool IncludeJson { get; set; } = true;

        [Category(FileTypes), DisplayName("Additional file extensions"), Description("Separate with ';' (e.g. .skin;.sitemap).")]
        [DefaultValue("")]
        public string AdditionalFileExtensions { get; set; } = string.Empty;

        [Category(Exclusions), DisplayName("Exclude generated code"), Description("*.designer.cs, *.g.cs, obj\\, <auto-generated>.")]
        [DefaultValue(true)]
        public bool IgnoreGeneratedCode { get; set; } = true;

        [Category(Exclusions), DisplayName("Exclude T4 generated code")]
        [DefaultValue(true)]
        public bool ExcludeT4GeneratedCode { get; set; } = true;

        [Category(Exclusions), DisplayName("Exclude paths (regular expressions)"), Description("Separate with ';'.")]
        [DefaultValue(SweepOptions.DefaultExcludePatterns)]
        public string ExcludePatterns { get; set; } = SweepOptions.DefaultExcludePatterns;

        public SweepOptions ToSweepOptions() => new SweepOptions
        {
            CleanupOnSave = CleanupOnSave,
            EnableRemoveUnusedLocalVariables = RemoveUnusedLocalVariables,
            EnableRemoveUnusedUsings = RemoveUnusedUsings,
            EnableSortUsings = SortUsings,
            EnableRemoveConsecutiveBlankLines = RemoveConsecutiveBlankLines,
            EnableFormatDocument = FormatDocument,
            IncludeCSharp = IncludeCSharp,
            IncludeVisualBasic = IncludeVisualBasic,
            IncludeWebForms = IncludeWebForms,
            RegenerateWebFormsDesigner = RegenerateWebFormsDesigner,
            IncludeRazor = IncludeRazor,
            IncludeHtml = IncludeHtml,
            IncludeXmlConfig = IncludeXmlConfig,
            IncludeXaml = IncludeXaml,
            IncludeStyles = IncludeStyles,
            IncludeScripts = IncludeScripts,
            IncludeJson = IncludeJson,
            AdditionalFileExtensions = AdditionalFileExtensions ?? string.Empty,
            IgnoreGeneratedCode = IgnoreGeneratedCode,
            ExcludeT4GeneratedCode = ExcludeT4GeneratedCode,
            ExcludePatterns = ExcludePatterns ?? string.Empty
        };
    }
}
