using System.ComponentModel;
using Community.VisualStudio.Toolkit;

namespace YelcoBot.CodeSweep.Infrastructure.VisualStudio.Settings
{
    public class GeneralOptions : BaseOptionModel<GeneralOptions>
    {
        [Category("Rules")]
        [DisplayName("Remove Unused Usings")]
        [Description("Automatically remove unused using directives (CS8019).")]
        [DefaultValue(true)]
        public bool EnableRemoveUnusedUsings { get; set; } = true;

        [Category("Rules")]
        [DisplayName("Sort Usings")]
        [Description("Sort using directives placing System.* directives first.")]
        [DefaultValue(true)]
        public bool EnableSortUsings { get; set; } = true;

        [Category("Rules")]
        [DisplayName("Remove Unused Local Variables")]
        [Description("Automatically remove unused local variables (CS0168 / CS0219).")]
        [DefaultValue(true)]
        public bool EnableRemoveUnusedLocalVariables { get; set; } = true;

        [Category("Rules")]
        [DisplayName("Remove Consecutive Blank Lines")]
        [Description("Remove consecutive empty lines leaving maximum one blank line.")]
        [DefaultValue(true)]
        public bool EnableRemoveConsecutiveBlankLines { get; set; } = true;

        [Category("Rules")]
        [DisplayName("Format Document")]
        [Description("Apply standard Roslyn document formatting according to .editorconfig.")]
        [DefaultValue(true)]
        public bool EnableFormatDocument { get; set; } = true;

        [Category("Automation")]
        [DisplayName("Automatic Cleanup On Save")]
        [Description("Automatically run CodeSweep when saving a C# document.")]
        [DefaultValue(false)]
        public bool CleanupOnSave { get; set; } = false;

        [Category("Automation")]
        [DisplayName("Ignore Generated Code")]
        [Description("Ignore generated code files (*.g.cs, *.designer.cs, <auto-generated>).")]
        [DefaultValue(true)]
        public bool IgnoreGeneratedCode { get; set; } = true;
    }
}
